require("prototypes.entity.index")
require("prototypes.technology.index")
require("prototypes.item.index")
require("prototypes.recipe.index")
require("prototypes.tiles.tiles")
require("prototypes.planet.planet")
require("prototypes.radiation")
require("prototypes.entity.oxidized-boiler")